---
sidebar: sidebar 
permalink: workflows_infra/wf_man_cluster.html 
keywords:  
summary: É possível gerenciar um cluster do Kubernetes para que as operações de proteção de dados possam ser executadas. 
---
= Gerenciar um cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
É possível gerenciar um cluster do Kubernetes para que a proteção de dados possa ser executada.



== Passo 1: Selecione o cluster a gerir

Execute o fluxo de trabalho link:../workflows_infra/wf_list_clusters.html["Listar clusters"] e selecione o cluster desejado. A propriedade `managedState` do cluster deve ser `unmanaged`.



== Passo 2: Opcionalmente, selecione a classe de armazenamento

Opcionalmente, execute o fluxo de trabalho link:../workflows_infra/wf_list_storage_classes.html["Listar classes de armazenamento"] e selecione a classe de armazenamento desejada.


NOTE: Se você não fornecer uma classe de armazenamento na chamada para gerenciar o cluster, sua classe de armazenamento padrão será usada.



== Etapa 3: Gerencie o cluster

Execute a seguinte chamada de API REST para gerenciar o cluster.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="1,6"]
|===
| Método HTTP | Caminho 


| POST | /Accounts/_id/topology/v1/managedclusters 
|===
.Curl exemplo
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/topology/v1/managedClusters" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Exemplo de entrada JSON
[source, json]
----
{
  "type": "application/astra-managedCluster",
  "version": "1.0",
  "id": "d0fdf455-4330-476d-bb5d-4d109714e07d"
}
----