---
sidebar: sidebar 
permalink: workflows_infra/workflows_infra_before.html 
keywords: workflows, infrastructure workflows, preparation 
summary: Use esses workflows para criar e manter a infraestrutura usada com uma implantação do Astra Control Center. Em muitos casos, os workflows também podem ser usados com o Astra Control Service. 
---
= Prepare-se para usar os workflows de infraestrutura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use esses workflows para criar e manter a infraestrutura usada com uma implantação do Astra Control Center. Em muitos casos, os workflows também podem ser usados com o Astra Control Service.


NOTE: Esses fluxos de trabalho podem ser expandidos e aprimorados pelo NetApp a qualquer momento, portanto, você deve revisá-los periodicamente.



== Preparação geral

Antes de usar qualquer um dos workflows do Astra, revise link:../get-started/prepare_to_use_workflows.html["Prepare-se para usar os fluxos de trabalho"]o .



== Categorias de fluxo de trabalho

Os fluxos de trabalho de infraestrutura são organizados em diferentes categorias para facilitar a localização do que você deseja.

[cols="25,75"]
|===
| Categoria | Descrição 


| Identidade e acesso | Esses fluxos de trabalho permitem gerenciar identidade e como o Astra é acessado. Os recursos incluem usuários, credenciais e tokens. 


| Configuração LDAP | Opcionalmente, você pode configurar o Astra Control Center para usar o LDAP para autenticar usuários selecionados. 


| Clusters | É possível adicionar clusters gerenciados do Kubernetes que permitem proteger e dar suporte às aplicações que eles contêm. 


| Nuvens | Esses workflows fornecem acesso às nuvens disponíveis por meio da API REST Astra Control. 


| Baldes | Você pode usar esses fluxos de trabalho para criar e gerenciar os buckets do S3 usados para armazenar backups. 


| Armazenamento | Esses fluxos de trabalho permitem adicionar e manter backends e volumes de armazenamento. 
|===