---
sidebar: sidebar 
permalink: rest-core/rest_web_services.html 
keywords: rest, web, web services 
summary: 'Representational State Transfer (REST) é um estilo para a criação de aplicações web distribuídas. Quando aplicado ao design de uma API de serviços da Web, ele estabelece um conjunto de tecnologias e práticas recomendadas principais para expor recursos baseados em servidor e gerenciar seus estados.' 
---
= Serviços web REST
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Representational State Transfer (REST) é um estilo para a criação de aplicações web distribuídas. Quando aplicado ao design de uma API de serviços da Web, ele estabelece um conjunto de tecnologias e práticas recomendadas principais para expor recursos baseados em servidor e gerenciar seus estados. Embora O REST forneça uma base consistente para o desenvolvimento de aplicativos, os detalhes de cada API podem variar com base nas escolhas específicas de design. Você deve estar ciente das características da API REST do Astra Control antes de usá-la com uma implantação ativa.



== Recursos e representação do Estado

Os recursos são os componentes básicos de um sistema baseado na Web. Ao criar um aplicativo REST de serviços da Web, as tarefas iniciais de design incluem:

* Identificação de recursos baseados em sistema ou servidor
+
Cada sistema usa e mantém recursos. Um recurso pode ser um arquivo, transação comercial, processo ou entidade administrativa. Uma das primeiras tarefas no projeto de um aplicativo baseado em serviços web REST é identificar os recursos.

* Definição de estados de recursos e operações de estado associadas
+
Os recursos estão sempre em um de um número finito de estados. Os estados, bem como as operações associadas usadas para afetar as mudanças de estado, devem ser claramente definidos.





== Pontos de extremidade URI

Todos os recursos REST devem ser definidos e disponibilizados usando um esquema de endereçamento bem definido. Os endpoints onde os recursos estão localizados e identificados usam um URI (Uniform Resource Identifier). O URI fornece uma estrutura geral para criar um nome exclusivo para cada recurso na rede. O Uniform Resource Locator (URL) é um tipo de URI usado com serviços da Web para identificar e acessar recursos. Os recursos são normalmente expostos em uma estrutura hierárquica semelhante a um diretório de arquivos.



== Mensagens HTTP

O Hypertext Transfer Protocol (HTTP) é o protocolo usado pelo cliente e servidor de serviços da Web para trocar mensagens de solicitação e resposta sobre os recursos. Como parte do projeto de um aplicativo de serviços da Web, os métodos HTTP são mapeados para os recursos e as ações de gerenciamento de estado correspondentes. HTTP está sem estado. Portanto, para associar um conjunto de solicitações e respostas relacionadas como parte de uma transação, informações adicionais devem ser incluídas nos cabeçalhos HTTP carregados com os fluxos de dados de solicitação e resposta.



== Formatação JSON

Embora as informações possam ser estruturadas e transferidas entre um cliente e um servidor de serviços da Web de várias maneiras, a opção mais popular é JavaScript Object Notation (JSON). JSON é um padrão da indústria para representar estruturas de dados simples em texto simples e é usado para transferir informações de estado descrevendo os recursos. A API REST DO Astra Control usa JSON para formatar os dados transportados no corpo de cada solicitação e resposta HTTP.
