---
sidebar: sidebar 
permalink: workflows/wf_create_snapshot.html 
keywords:  
summary: Você pode criar um instantâneo para um aplicativo específico. 
---
= Crie um instantâneo para um aplicativo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode criar um instantâneo para um aplicativo específico.



== Antes de começar

Você deve ter o ID do aplicativo para o qual deseja criar um instantâneo. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste as aplicações"] para localizar o aplicativo.



== Criar um instantâneo

Execute a seguinte chamada de API REST.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| POST | /Accounts/_id/k8s/v1/apps//app_id/appSnaps 
|===
.Parâmetros de entrada adicionais
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação | Caminho | Sim | Identifica o aplicativo gerenciado onde o snapshot será criado. 


| JSON | Corpo | Sim | Fornece os parâmetros para o instantâneo. Veja o exemplo abaixo. 
|===
.Curl exemplo: Crie um instantâneo para o aplicativo
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v1/apps/$APP_ID/appSnaps" \
--include \
--header "Content-Type: application/astra-appSnap+jso" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.Exemplo de entrada JSON
[source, json]
----
{
  "type": "application/astra-appSnap",
  "version": "1.1",
  "name": "snapshot-david-1"
}
----