---
sidebar: sidebar 
permalink: workflows/wf_get_man_app.html 
keywords:  
summary: Você pode recuperar todas as variáveis de recurso descrevendo um único aplicativo. 
---
= Obtenha uma aplicação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode recuperar todas as variáveis de recurso descrevendo um único aplicativo.



== Antes de começar

Você deve ter o ID do aplicativo que deseja recuperar. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste as aplicações"] para localizar o aplicativo.



== Passo 1: Obtenha o aplicativo

Execute a seguinte chamada de API REST.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /accounts/_id/k8s/v2/apps//app_id 
|===
.Parâmetros de entrada adicionais
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação | Caminho | Sim | Valor de ID da aplicação a recuperar. 
|===
.Curl exemplo: Retorna todos os dados para o aplicativo
[source, curl]
----
curl --request GET \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps/$APP_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----