---
sidebar: sidebar 
permalink: workflows/wf_unmanage_app.html 
keywords:  
summary: Você pode remover um aplicativo gerenciado quando não for mais necessário. A remoção de um aplicativo gerenciado também exclui as programações associadas. 
---
= Desgerenciar um aplicativo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode remover um aplicativo gerenciado quando não for mais necessário. A remoção de um aplicativo gerenciado também exclui as programações associadas.



== Antes de começar

Você deve ter o ID do aplicativo que deseja desgerenciar. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste as aplicações"] para localizar o aplicativo.

Os backups e snapshots do aplicativo não são removidos automaticamente quando são excluídos. Se você não precisar mais dos backups e snapshots, exclua-os antes de remover o aplicativo.



== Desgerenciar o aplicativo

Execute a seguinte chamada de API REST para remover o aplicativo.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| ELIMINAR | /accounts/_id/k8s/v2/apps//app_id 
|===
.Parâmetros de entrada adicionais
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação | Caminho | Sim | Identifica o aplicativo a ser removido. 
|===
.Curl exemplo: Remover um aplicativo gerenciado
[source, curl]
----
curl --request DELETE \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps/$APP_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----