---
sidebar: sidebar 
permalink: workflows/workflows_before.html 
keywords: workflows, management workflows, preparation 
summary: Use esses workflows como parte da administração das aplicações em um cluster gerenciado do Astra. 
---
= Prepare-se para usar os fluxos de trabalho de gerenciamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Use esses workflows como parte da administração das aplicações em um cluster gerenciado do Astra.


NOTE: Esses fluxos de trabalho podem ser expandidos e aprimorados pelo NetApp a qualquer momento, portanto, você deve revisá-los periodicamente.



== Preparação geral

Antes de usar qualquer um dos workflows do Astra, revise link:../get-started/prepare_to_use_workflows.html["Prepare-se para usar os fluxos de trabalho"]o .



== Categorias de fluxo de trabalho

Os fluxos de trabalho de gerenciamento são organizados em diferentes categorias para facilitar a localização do que você deseja.

[cols="25,75"]
|===
| Categoria | Descrição 


| Controlo de aplicação | Esses fluxos de trabalho permitem que você controle os aplicativos gerenciados e não gerenciados. Você pode listar os aplicativos, bem como criar e remover um aplicativo gerenciado. 


| Proteção de aplicação | Use esses fluxos de trabalho para proteger suas aplicações gerenciadas por meio de snapshots e backups. 


| Clonagem e restauração de aplicações | Esse fluxo de trabalho descreve como clonar e restaurar aplicativos gerenciados. 


| Suporte | Há vários fluxos de trabalho disponíveis para depurar e dar suporte às suas aplicações, bem como o ambiente geral do Kubernetes. 
|===


== Considerações adicionais

Há várias considerações adicionais ao usar os fluxos de trabalho de gerenciamento.



=== Clonar uma aplicação

Há algumas coisas a considerar ao clonar um aplicativo. Os parâmetros descritos abaixo fazem parte da entrada JSON.

Identificador do cluster de origem:: O valor de `sourceClusterID` sempre identifica o cluster onde o aplicativo original está instalado.
Identificador de cluster:: O valor de `clusterID` identifica o cluster onde o novo aplicativo será instalado.
+
--
* Ao clonar dentro do mesmo cluster `clusterID` e `sourceClusterID` ter o mesmo valor.
* Ao clonar entre clusters, os dois valores são diferentes e `clusterID` devem ser a ID do cluster de destino.


--
Namespaces:: O `namespace` valor deve ser diferente do aplicativo de origem original. Além disso, o namespace para o clone não pode existir e o Astra o criará.
Backups e snapshots:: Opcionalmente, você pode clonar um aplicativo a partir de um backup ou snapshot existente usando os `backupID` parâmetros ou `snapshotID`. Se você não fornecer um backup ou snapshot, o Astra criará primeiro um backup da aplicação e, em seguida, clonará a partir do backup.




==== Restaurar uma aplicação

Aqui estão algumas coisas a considerar ao restaurar um aplicativo.

* Restaurar um aplicativo é muito semelhante à operação clone.
* Ao restaurar um aplicativo, você deve fornecer um backup ou um snapshot.

